apiVersion: v1
kind: Namespace
metadata:
  name: apps-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: apps-argocd
  namespace: apps-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  server:
    route:
      enabled: true
  rbac:
    policy: 'g, system:cluster-admins, role:admin'
    scopes: '[groups]'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: apps-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://github.com/nsaraiya-rh/openshift-acm-gitops-new-2.git
    targetRevision: HEAD
    path: apps/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
